[font]
size = 13.4

[font.bold]
family = "Liga SFMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Liga SFMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Liga SFMono Nerd Font"
style = "Italic"

[font.normal]
family = "Liga SFMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0
