- name: Create Brave Apps
  template:
    src: "~/dot/ansible/roles/web/templates/app.j2"
    dest: "~/.local/share/applications/brave-{{item.name | lower | regex_replace(' ', '-')}}.desktop"
  loop:
    - { name: "Gmail", url: "https://mail.google.com/mail/u/0/#inbox" }
    - { name: "WhatsApp", url: "https://web.whatsapp.com/" }
    - { name: "Notion", url: "https://notion.so/" }
    - { name: "Twitter", url: "https://twitter.com/home", icon: "web-twitter" }
    - {
        name: "Google Keep",
        url: "https://keep.google.com/u/0/",
        icon: "notes",
      }
    - {
        name: "Google Calendar",
        url: "https://calendar.google.com/calendar/u/0/r",
      }
    - {
        name: "YouTube Music",
        url: "https://music.youtube.com",
        icon: "youtube-music-desktop-app",
      }
    - {
        name: "Messenger",
        url: "https://www.messenger.com/",
        icon: "messengerfordesktop",
      }

- name: Brave Launcher
  copy:
    dest: ~/.local/bin/brave-launcher
    mode: "0755"
    content: |-
      #!/bin/sh

      XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
      BRAVE_USER_FLAGS_FILE="$XDG_CONFIG_HOME/brave-flags.conf"
      if [[ -f $BRAVE_USER_FLAGS_FILE ]]; then
          USER_FLAGS="$(cat $BRAVE_USER_FLAGS_FILE | sed 's/#.*//')"
      fi

      /usr/bin/brave-browser-beta $@ $USER_FLAGS

- name: Shadow Brave App
  copy:
    dest: ~/.local/share/applications/brave-browser-beta.desktop
    src: /usr/share/applications/brave-browser-beta.desktop

- name: Use Brave Launcher
  ansible.builtin.replace:
    path: ~/.local/share/applications/brave-browser-beta.desktop
    regexp: "^Exec=/usr/bin/brave-browser-beta"
    replace: "Exec={{ lookup('env', 'HOME') }}/.local/bin/brave-launcher"
